# Generated by Django 3.0.3 on 2020-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20200210_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Slug name'),
        ),
    ]
