# Generated by Django 2.2.10 on 2020-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20200215_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.IntegerField(choices=[(1, 'cold'), (2, 'medium'), (3, 'warm')], verbose_name='Temperature'),
        ),
    ]
