# Generated by Django 2.2.10 on 2020-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20200215_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='draft',
            field=models.BooleanField(blank=True, default=False, verbose_name=''),
        ),
    ]
